### PR TITLE
if Null, make properties an empty dict

### PR DESCRIPTION
**Pull request by aryanbhosale**
# Pull Request

## Description

Made the properties an empty dictionary if found to be null 

Fixes #

#18 

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by aryanbhosale** [comment]
Hi @peterdudfield , so sorry for the delay, I was really busy prepping for my quizzes that i had today and have for the next 2 days:(
But ive made the changes and tested it, it doesnt give the same error it did last time and i think we can try running tests here
could you please review it and let me know if this is what was expected?
thank you :)

**Comment by peterdudfield** [comment]
> Hi @peterdudfield , so sorry for the delay, I was really busy prepping for my quizzes that i had today and have for the next 2 days:( But ive made the changes and tested it, it doesnt give the same error it did last time and i think we can try running tests here could you please review it and let me know if this is what was expected? thank you :)

Ive changed the branch to development, as last time the tests failed on main. 

Have you run the test locally? Do they work?

**Comment by aryanbhosale** [comment]
> > Hi @peterdudfield , so sorry for the delay, I was really busy prepping for my quizzes that i had today and have for the next 2 days:( But ive made the changes and tested it, it doesnt give the same error it did last time and i think we can try running tests here could you please review it and let me know if this is what was expected? thank you :)
> 
> Ive changed the branch to development, as last time the tests failed on main.
> 
> Have you run the test locally? Do they work?

Ive made the changes , but im running into these errors:
image
image
image

**Comment by aryanbhosale** [comment]
> > > > Hi @peterdudfield , so sorry for the delay, I was really busy prepping for my quizzes that i had today and have for the next 2 days:( But ive made the changes and tested it, it doesnt give the same error it did last time and i think we can try running tests here could you please review it and let me know if this is what was expected? thank you :)
> > > 
> > > 
> > > Ive changed the branch to development, as last time the tests failed on main.
> > > Have you run the test locally? Do they work?
> 
> I ran `export PYTHONPATH=${PYTHONPATH}:./forecast_blend` first and then pytest now i see this error: image

Hi @peterdudfield , ive fixed this in my latest commit, i think this can be merged, could you please review it?

**Comment by peterdudfield** [comment]
Excellent, looks, good. Could you remove all the pycache files and then ill merge?

**Pull request merged**
